// EVENTS
/*

HTML events are things that happen to HTML elements.

Examples of events:

An HTML button is clicked
A web page has finished loading
The mouse moves over an element
A keyboard key is pressed
An HTML input field is changed

JavaScript Events
Often, when events happen, you may want to do something.

When JavaScript is used in HTML pages, JavaScript can react on events.

JavaScript lets you execute code when events are detected.

HTML allows event handler attributes, with JavaScript code, to be added to HTML elements.

*/ 

// Syntax

//with single quotes
// <element event='some JavaScript code'>

//with double quotes
// <element event="some JavaScript code">

//do example one

//In the example above, the JavaScript code changes the content of the element with id="demo".

//In the next example, the code changes the content of its own element using this.innerHTML:

//Do example 2

//Calling a JavaScript Function
//  JavaScript code can often be several lines long.It is more common to use the event attribute to call a functions:

// do example 3

/*
Event	Description
onchange	An HTML element has been changed
onclick	The user clicks an HTML element
onmouseover	The user moves the mouse over an HTML element
onmouseout	The user moves the mouse away from an HTML element
onkeydown	The user pushes a keyboard key
onload	The browser has finished loading the page


Using an Event Listener
Using event attributes like onclick are easy to use.

Nevertheless, using addEventListener() is the recommended way to handle events.
*/

//do example 4


//MOUSE EVENTS
/*
Mouse Events happen when the user interacts with the mouse.

Common Mouse Events:

click - Fires after both a mousedown and mouseup event occur on the same element with the main mouse button (usually the left).

dblclick - Fires after two rapid clicks on the same element.

mouseover - Fires when the pointer moves over an element (or one of its children).

mouseout - Fires when the pointer leaves an element.

mousemove - Fires continuously as the mouse pointer moves over an element, providing positional information (coordinates) about the cursor.

mousedown / mouseup -These events fire when a mouse button is pressed down (mousedown) or released (mouseup) over an element, respectively.
*/


// KeyBoard Events
/*
Keyboard Events happen when the user presses a key on the keyboard:

keydown (key is pressed down)
keyup (key is released)
keypress (deprecated)


Note
keypress only fires for character keys (a or 5), not for control keys (alt or backspace).

Developers are advised to use keydown or keyup instead.
*/

// do example 1 for keyboard events

// ====== Timing Events =========

//Timing is driven by Timing Events generated by the system clock.
// Timing events are used to schedule code execution at specified time intervals.

// Common Timing Events:
// setTimeout(function, milliseconds) - Executes a function once after a specified number of milliseconds.
// setInterval(function, milliseconds) - Repeatedly executes a function at specified time intervals (in milliseconds) until stopped.
// clearTimeout(timeoutID) - Stops a function that was set to execute with setTimeout().
// clearInterval(intervalID) - Stops a function that was set to execute repeatedly with setInterval().

// === A clock ==
// do example for clock


// SetTimeout Method

// the setTimeout() method calls a function or evaluates an expression after a specified number of milliseconds.
//The setTimeout() Method
//The setTimeout() method executes a function after a delay in milliseconds.

/*
setTimeout(function, delay, p1,...,pN)
Parameters
Parameter	Description
function	Required.
The function to be called when the timer expires.
delay	Optional.
The milliseconds the timer should wait.
Defalt 0 (immediately).
p1,...,pN	Optional.
Arguments passed to the function.
Return Value
Type	Description
Integer	An integer that uniquely identifies the timer.
This "timeout ID" can later be passed to clearTimeout() to cancel the timer.
*/

// do example for setTimeout


// ===== SetInterval Method ======
// The setInterval() method calls a function or evaluates an expression at specified intervals (in milliseconds).
// The setInterval() method will continue calling the function until clearInterval() is called, or the window is closed.

/*
The SetInterval()Method
The setInterval() method calls a function repeatedly.

setInterval(function, delay, p1,...,pN)
Parameters
Parameter	Description
function	Required.
The function to be called for every interval.
delay	Optional.
The milliseconds between each function call.
Defalt 0.
p1,...,pN	Optional.
Arguments passed to the function.
Return Value
Type	Description
Integer	An integer that uniquely identifies the timer.
This "timeout ID" can later be passed to clearInterval() to cancel the timer.
*/

// do example for setInterval



// ====== DOM MANIPULATION ====

// DOM selectors

//DOM stands for Document Object Model. It's a programming interface for HTML and XML documents that represents the web page as a structured tree of objects that JavaScript can interact with.

/*
HTML (Grandparent)
├── HEAD (Parent)
│   ├── TITLE (Child)
│   └── META (Child)
└── BODY (Parent)
    ├── H1 (Child)
    ├── P (Child with text)
    └── DIV (Child)
        └── BUTTON (Grandchild)
        */

        //The HTML DOM is a tree of Nodes that represents an HTML Page.

        //The DOM Tree
//When a web page loads, the browser creates a tree-like representation of the HTML document.

//Each part of the document are nodes in the tree:

//Class work
// 1. Create a simple html page with an empty <p> element. Give it any id you like. write a js script that will add some text to the <p> element when the page loads.


// DOM Selectors
//DOM selectors are methods used to select and manipulate HTML elements in the DOM.
//Common DOM Selectors:

//  1. getElementById(): Selects a single element by its unique ID.
//  2. getElementsByClassName(): Selects all elements with a specific class name.
// 3. getElementsByTagName(): Selects all elements with a specific tag name.
// 4. querySelector(): Selects the first element that matches a specified CSS selector.
// 5. querySelectorAll(): Selects all elements that match a specified CSS selector.

// Do examples for getElementById

//Create method()

// What does the create method do?
// The create method creates a new HTML element specified by tagName.
// Syntax: document.createElement(tagName)

// do example for create method

// appendChild() method
// The appendChild() method adds a new child node to an element as the last child node.
// Syntax: parentNode.appendChild(childNode)
// do example for appendChild

//Remove method
// The remove() method removes the specified element from the DOM.
// Syntax: element.remove()
// do example for remove method


// ===== FORMS AND USER INPUT HANDLING =========

// Forms are a crucial part of web development, allowing users to input and submit data. JavaScript can be used to handle form events, validate user input, and enhance the user experience.

// Common Form Events:
// submit - Fires when a form is submitted.
// change - Fires when the value of an input element changes.
// input - Fires when the value of an input element is changed (for text inputs).
// focus - Fires when an element gains focus.
// blur - Fires when an element loses focus.

